language: cpp

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

install:
  - sudo pip install cpp-coveralls --use-mirrors

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on -DBUILD_TESTS_WITH_EIGEN=on ..

script:
  - make && ctest -V

after_success:
  - if [ "$CXX" == "g++" && "$BUILD_TYPE" == "Debug" ]; then coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*test/.*.cpp.*"; fi