language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

before_install:
 - sudo apt-get install libeigen3-dev

install:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on ..
  - make
  - cd ..

script:
  - cd build
  - ctest -V