language: cpp

compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

install:
  - cmake -HSML -Bbuild -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TESTS=on -DBUILD_WITH_EIGEN=on
  - cd build
  - make
  - cd ..

script:
  - cd build
  - ctest -V