language: cpp

compiler:
  - clang
  - gcc

env:
  - if [ "$CXX" = "g++" ]; then TEST_COVERAGE=on; else TEST_COVERAGE=off; fi

install:
  - if [ "$CXX" = "g++" ]; then sudo apt-get install lcov rubygems; fi
  - if [ "$CXX" = "g++" ]; then gem install lcoveralls; fi

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug -DRUN_TEST_COVERAGE=$TEST_COVERAGE -DBUILD_TESTS=on -DBUILD_TESTS_WITH_EIGEN=on ..

script:
  - make && ctest -V

after_success:
  - if [ "$CXX" = "g++" ]; then make test_coverage && lcoveralls --retry-count 5; fi