language: cpp

compiler:
  - gcc
  - clang

env:
  - BUILD_TYPE=Debug

install:
  - sudo pip install cpp-coveralls --use-mirrors

before_script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DRUN_TEST_COVERAGE=on -DBUILD_TESTS=on -DBUILD_TESTS_WITH_EIGEN=on ..

script:
  - make && ctest -V

after_success:
  - coveralls --root .. -E ".*external.*" -E ".*CMakeFiles.*" -E ".*tests/.*.cpp.*"